version: "0.2"
ignorePaths:
  - .gitignore
  - requirements.txt
  - alembic*
  - bart-bot.content.yaml
allowCompoundWords: true
dictionaries:
  - python
words:
  - apscheduler
  - clsname
  - grnd
  - isort
  - Misha
  - mypy
  - no_photos
  - ondelete
  - onupdate
  - persistences
  - psycopg
  - pydantic
  - pytest
  - sqlalchemy
  - testdb
  - venv
  - vybornyy
  - yadisk
  - feedme
ignoreWords: []
import: []
enableFiletypes:
  - dockercompose
  - ini
  - makefile
  - markdown
  - toml
