[tool.pytest.ini_options]
testpaths = [
    'tests'
]
markers = []
addopts = []
pythonpath = 'src'

[tool.mypy]
exclude = [
    'venv',
    '.*tmp.*',
    '.*untitled.*',
]
plugins = [
  'pydantic.mypy'
]

ignore_missing_imports = true
follow_imports = 'silent'
warn_redundant_casts = true
warn_unused_ignores = true
check_untyped_defs = true
no_implicit_reexport = true
no_implicit_optional = false
#disallow_untyped_defs = true  # for strict mypy


[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true


[tool.black]
line-length = 120                   # max line length
skip-string-normalization = 1       # disable converting single quote to double
# by default black exclude all .gitignore files. here is regex pattern to extend this list
# NOTE! list of files name is not supported, only regex patterns
# WARNING! also pass this list of files to pre-commit-config.
# extend-exclude = 'alembic/|migrations/'

[tool.isort]
skip_glob = '*tmp*'
profile = 'black'


[tool.autoflake]
exclude = ['venv', 'alembic', '*tmp*'] # WARNING! also pass this list of files to pre-commit-config.


[tool.flake8]
max-line-length = 120
extend-ignore = [
    'E731',     # assignment lambda to variable - okay
]
per-file-ignores = [
    '*/__init__.py:F401',  # imported but unused
]
exclude = [
    'venv/*',
    'alembic/*',
    '*tmp*',
    '*untitled*',
]