"""empty message

Revision ID: 6e4e34672fd8
Revises:
Create Date: 2023-03-01 09:52:28.305207

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '6e4e34672fd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'storage',
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'user',
        sa.Column('storage_id', sa.BIGINT(), nullable=False),
        sa.Column('storage_request_id', sa.BIGINT(), nullable=True),
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(
            ['storage_id'],
            ['storage.id'],
        ),
        sa.ForeignKeyConstraint(
            ['storage_request_id'],
            ['storage.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'message',
        sa.Column('user_id', sa.BIGINT(), nullable=False),
        sa.Column('message_id', sa.BIGINT(), nullable=False),
        sa.Column('media_id', sa.String(), nullable=True),
        sa.Column('media_type', sa.VARCHAR(length=256), nullable=True),
        sa.Column('media_group_id', sa.String(), nullable=True),
        sa.Column('json', sa.JSON(), nullable=False),
        sa.Column('id', sa.BIGINT(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('user')
    op.drop_table('storage')
    # ### end Alembic commands ###
