name: tests
on: push

env:
  PROJECT_NAME: bart-bot

  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DB_NAME: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

jobs:
  Tests:
    runs-on: ubuntu-latest
    container: python:3.10-slim
    services:
      database:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Test pytest
        run: pytest -vv -s

      - name: Test flake8
        run: |
          flake8 .

      - name: Test mypy
        run: |
          mypy .
