name: github-ci.yml
on: push

env:
  PROJECT_NAME: bart-bot

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Test flake8
        run: |
          flake8 .

      - name: Test mypy
        run: |
          mypy .

      - name: Test pytest
        run: pytest -vv -s
